export { default as Footer } from './footer/footer'
export { default as Header } from './header/header'
export { default as Loading } from './loading/loading'
export { default as Logo } from './logo/logo'
export { default as Status } from './status/status'
export { default as Router } from './router/router'
